export const loginFields = [
  {
    type: "email",
    fieldname: "Email",
    id: "email",
    name: "email",
    autocomplete: "email",
    placeholder: " ",
    pattern: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
    errMsg: 'Please enter valid Email!',
    "aria-invalid": "true",
    "ariaErrormessage": "email_error",
  },
  {
    type: "password",
    fieldname: "Password",
    id: "password",
    name: "password",
    autocomplete: "password",
    placeholder: " ",
    pattern: /^.{1,}$/,
    errMsg: 'Please enter password!',
    "aria-invalid": "true",
    "ariaErrormessage": "password_error",
  },
];
